#!/bin/bash

EIS_VER=v2.0.99
PRE_VER=v2.0.2
MQTT_BUS_TAG=${PRE_VER}
API_GW_TAG=${PRE_VER}
NODE_RED_TAG=${PRE_VER}
WSN_SIMULATOR_TAG=${PRE_VER}
WSN_DEV_TAG=${PRE_VER}
DUST_LINK_TAG=${PRE_VER}
HDD_PMQ_TAG=${PRE_VER}
BT_SIMULATOR_TAG=${EIS_VER}

echo "MQTT_BUS_TAG=${MQTT_BUS_TAG}" > .env
echo "API_GW_TAG=${API_GW_TAG}" >> .env
echo "NODE_RED_TAG=${NODE_RED_TAG}" >> .env
echo "WSN_SIMULATOR_TAG=${WSN_SIMULATOR_TAG}" >> .env
echo "WSN_DEV_TAG=${WSN_DEV_TAG}" >> .env
echo "DUST_LINK_TAG=${DUST_LINK_TAG}" >> .env
echo "HDD_PMQ_TAG=${HDD_PMQ_TAG}" >> .env
echo "BT_SIMULATOR_TAG=${BT_SIMULATOR_TAG}" >> .env
