version: '2'


services:

  advigw-bt-simulator:
   image: advigw4x86/bt-simulator:v2.0.3
   container_name: advigw-bt-simulator
   restart: always
   depends_on:
    - advigw-mqtt-bus
   networks:
    - advigw-network   
   logging:
    options:
     max-size: 5M
  
   

networks:
 advigw-network:
