version: '2'


services:
  
  advigw-mqtt-bus:
   image: advigw4x86/mqtt-bus:v2.0.2
   container_name: advigw-mqtt-bus
   restart: always
   networks: 
    - advigw-network
   ports:
    - 1883:1883
   logging:
    options:
     max-size: 5M


  advigw-api-gw:
    image: advigw4x86/api-gw:v2.0.3
    container_name: advigw-api-gw
    restart: always
    networks:
     - advigw-network
    ports:
     - 3000:3000
    logging:
     options:
      max-size: 10M
    
  advigw-node-red:
   image: advigw4x86/node-red:v2.0.2
   container_name: advigw-node-red
   restart: always
   networks: 
    - advigw-network
   ports:
    - 1880:1880
   logging:
    options:
     max-size: 10M


  advigw-hdd-pmq:
   image: advigw4x86/hdd-failure-predict:v2.0.2
   container_name: advigw-hdd-pmq
   restart: always
   networks: 
    - advigw-network
   logging:
    options:
     max-size: 10M

networks:
  advigw-network:

 
